#!/usr/bin/ksh
Tmp="/tmp/$$"
TmpDir="/tmp/dir$$"
trap 'rm -f "$Tmp" >/dev/null 2>&1' 0
trap "exit 2" 1 2 3 13 15
rm $Tmp  >/dev/null 2>&1

if [ $# -eq 0 ] ; then
                 vim -c MRU
else
                 vim -o $1 $2 $3 $4
fi
